name: Auto Update Config Timestamp

on:
  push:
    paths:
      - 'background.png'

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update timestamp in config.json
        run: |
          # Tạo số timestamp (ví dụ: 1697431811)
          TIMESTAMP=$(date +%s)
          
          # Cập nhật vào key "update" trong file config.json
          jq ".update = \"$TIMESTAMP\"" config.json > temp.json && mv temp.json config.json
          
          echo "Updated timestamp to $TIMESTAMP"

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add config.json
          git commit -m "Bot: Update background timestamp $TIMESTAMP" || exit 0
          git push
