name: Auto Update Config Background Timestamp

on:
  push:
    paths:
      - 'background/background.png'
jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update timestamp in configbackground.json
        id: update_step
        run: |
          # 1. Tạo số timestamp mới
          TIMESTAMP=$(date +%s)
          
          # 2. Tạo date theo giờ Việt Nam (UTC+7)
          DATE=$(TZ='Asia/Ho_Chi_Minh' date '+%d/%m/%Y %H:%M:%S')
          
          # 3. Sử dụng --arg để truyền biến an toàn vào jq (Đã sửa .timetamp thành .timestamp)
          jq --arg ts "$TIMESTAMP" --arg dt "$DATE" '.timestamp = $ts | .date = $dt' configbackground.json > temp.json
          
          # 4. Sử dụng Regex để tìm 'background' và thay bằng timestamp mới
          sed -i -E "s|content://tvlauncher.config/background(/[0-9/]+)?|content://tvlauncher.config/background/$TIMESTAMP|g" temp.json
          
          mv temp.json configbackground.json
          
          # 5. Đẩy biến lên hệ thống để step sau nhận được
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
          
          echo "Updated configbackground.json with timestamp: $TIMESTAMP"
          echo "Updated configbackground.json with date (VN time): $DATE"

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add configbackground.json
          # Sử dụng biến nhận từ step trước qua ngữ cảnh github outputs
          git commit -m "Bot: Update background timestamp ${{ steps.update_step.outputs.timestamp }}" || exit 0
          git push
