name: Auto Update Config Background Timestamp

on:
  push:
    paths:
      - 'background/background.png'

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update timestamp in configbackground.json
        run: |
          # 1. Tạo số timestamp mới
          TIMESTAMP=$(date +%s)
          
          # 2. Tạo date theo giờ Việt Nam (UTC+7)
          DATE=$(TZ='Asia/Ho_Chi_Minh' date '+%d/%m/%Y %H:%M:%S')
          
          # 3. Cập nhật cả timestamp và date bằng jq
          jq ".timetamp = \"$TIMESTAMP\" | .date = \"$DATE\"" configbackground.json > temp.json
          
          # 4. Sử dụng Regex để tìm 'background' và thay bằng timestamp mới
          sed -i -E "s|content://tvlauncher.config/background(/[0-9/]+)?|content://tvlauncher.config/background/$TIMESTAMP|g" temp.json
          
          mv temp.json configbackground.json
          
          echo "Updated configbackground.json with timestamp: $TIMESTAMP"
          echo "Updated configbackground.json with date (VN time): $DATE"

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add configbackground.json
          git commit -m "Bot: Update background timestamp $TIMESTAMP" || exit 0
          git push
